version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PORT=5000
      - HOST=0.0.0.0
      - SECRET_KEY=dev-secret-key
      - DEFAULT_TIMEZONE=America/New_York
      - DISPLAY_TIMEZONE=America/New_York
      - USE_UTC_STORAGE=true
    volumes:
      - ./database:/app/database
      - ./data:/app/data
      - ./orchestrator:/app/orchestrator
      - ./pipelines:/app/pipelines
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 