version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "5001:5001"
    environment:
      # Change these credentials for your team
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=change-this-admin-password
      - TEAM_USERNAME=team
      - TEAM_PASSWORD=change-this-team-password
      - SECRET_KEY=change-this-secret-key-to-something-secure
      - FLASK_ENV=production
    volumes:
      - ./data:/app/data
      - ./database:/app/database
    restart: unless-stopped
    
  # Optional: Add nginx for SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dashboard
    restart: unless-stopped 