# Railway configuration for persistent database storage
# This ensures all team members get the same volume configuration

[deploy]
  startCommand = "python orchestrator/app.py"

# Volume configuration for persistent SQLite databases
[[volumes]]
  name = "database-storage"
  mountPath = "/app/database"

# Environment optimizations
[build]
  # Ensure proper Python environment
  buildCommand = "pip install -r requirements.txt"

# Service configuration
[service]
  # Allow sufficient time for database operations
  healthcheckTimeout = 300
  healthcheckInterval = 30 