# Railway configuration for persistent database storage
[deploy]
  startCommand = "python launcher.py"

# Volume configuration for persistent SQLite databases
[[volumes]]
  name = "database-storage"
  mountPath = "/app/database"

# Service configuration
[service]
  # Allow sufficient time for database operations
  healthcheckTimeout = 300
  healthcheckInterval = 30 