name: "conversion_rates_debug"
display_name: "Conversion Rates Debug"
description: "Debug and validation tools for the assigned conversion rates processing pipeline"
version: "1.0.0"
enabled: true
author: "Analytics Team" 