name: meta_pipeline
description: Meta pipeline for processing and analyzing meta data with advanced analytics
steps:
- file: 01_update_meta_data.py
  id: update_meta_data
  tested: false
  description: Update Meta advertising data from most recent date to today 